# Generated by Django 5.1.2 on 2024-10-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "SocialMedia",
            "0005_remove_friendrequest_reciever_friendrequest_receiver_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friendship",
            name="created_at",
        ),
    ]
