# Generated by Django 5.1.2 on 2024-10-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0006_remove_friendship_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True,
                default="profile_pics/default.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
