# Generated by Django 5.1.2 on 2024-10-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0007_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, default="images/default.png", null=True, upload_to="images"
            ),
        ),
    ]
