# Generated by Django 5.1.2 on 2024-10-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0009_alter_profile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
