# Generated by Django 5.1.2 on 2024-10-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0010_profile_bio_profile_pronouns"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="content",
            new_name="body",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="date_added",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="author",
        ),
        migrations.AddField(
            model_name="comment",
            name="name",
            field=models.CharField(default="Anonymous", max_length=255),
        ),
    ]
