# Generated by Django 5.1.2 on 2024-10-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SocialMedia", "0012_post_likes_delete_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_short",
            field=models.BooleanField(default=False),
        ),
    ]
